import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Linkbrary Home</title>
        {/* <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <header>
        <nav>
          <ul>
            <li>
              <Link href={{ pathname: '/folder' }}>folder page</Link>
            </li>
            <li>
              <Link href={{ pathname: '/shared' }}>shared page</Link>
            </li>
            <li>
              <Link href={{ pathname: '/test' }}>test page</Link>
            </li>
            <li>
              <Link href={{ pathname: '/signin' }}>signin page</Link>
            </li>
          </ul>
        </nav>
      </header>
      <main>빈페이지</main>
    </>
  );
}
