import Head from 'next/head';
import Link from 'next/link';

const fontSize = { fontSize: 'Large' };

export default function Home() {
  return (
    <>
      <Head>
        <title>Linkbrary Home</title>
        {/* <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' /> */}
      </Head>
      <header>
        <nav>
          <ul>
            <li>
              <Link href={{ pathname: '/folder' }} style={fontSize}>
                folder page
              </Link>
            </li>
            <li>
              <Link href={{ pathname: '/shared' }} style={fontSize}>
                shared page
              </Link>
            </li>
            <li>
              <Link href={{ pathname: '/test' }} style={fontSize}>
                test page
              </Link>
            </li>
            <li>
              <Link href={{ pathname: '/signin' }} style={fontSize}>
                signin page
              </Link>
            </li>
          </ul>
        </nav>
      </header>
      <main>빈페이지</main>
    </>
  );
}
